apiVersion: v1
kind: ReplicationController
metadata:
  name: hwnode
  labels:
    app: hwnode
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hwnode
  template:
    metadata:
      labels:
        app: hwnode
    spec:
      containers:
      - name: hwnode
        image: sandjaie/hwnode:latest
        ports:
        - containerPort: 8000

